In [71]:
import pickle

In [72]:
with open('02_scoreSeeds_4/packaged_binder_complex_data_2.pkl', 'rb') as file:
    complex_data = pickle.load(file)
complex_data.keys()

dict_keys(['msas', 'features', 'ppoe', 'seq_lens', 'focuses', 'contact_idxs', 'src_key_mask', 'term_lens', 'X', 'x_mask', 'seqs', 'ids', 'chain_idx', 'gvp_data', 'sortcery_seqs', 'sortcery_nrgs', 'sscore', 'flex', 'flex_mask', 'chain_lens', 'res_info', 'binder_chain_id'])

In [73]:
complex_data['seq_lens'].shape

torch.Size([1])

In [74]:
complex_data['seq_lens']

tensor([119])

In [75]:
complex_data['seqs']

tensor([[ 0, 19,  4,  9,  2,  4,  2,  3, 14,  0,  9,  8,  3, 18, 14,  8,  9,  5,
         15, 16, 17, 14,  3, 13,  9,  8,  8,  8,  9, 17,  3, 17,  9,  3, 15, 12,
         14,  7,  3,  0, 11,  8,  9, 14,  5, 10, 12,  2,  1, 19,  8,  7,  8,  9,
         14, 15, 15,  5, 19, 14,  9, 17, 19, 13, 17,  7,  2,  3,  8, 17, 17, 17,
          4, 17,  7, 15, 17,  5,  8, 14,  3, 14, 13, 12,  4,  6,  2,  9, 15,  0,
          3,  5, 15,  2,  3,  2,  0,  3,  9, 17,  3,  7, 17,  8,  3, 14, 12,  6,
         16, 17, 15,  0,  2, 11,  7, 15, 17, 12, 13]])

In [76]:
complex_data['ids']

['seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247']

In [77]:
with open('02_scoreSeeds_2/packaged_binder_complex_data_0.pkl', 'rb') as file:
    seed_data = pickle.load(file)
seed_data.keys()

dict_keys(['msas', 'features', 'ppoe', 'seq_lens', 'focuses', 'contact_idxs', 'src_key_mask', 'term_lens', 'X', 'x_mask', 'seqs', 'ids', 'chain_idx', 'gvp_data', 'sortcery_seqs', 'sortcery_nrgs', 'sscore', 'flex', 'flex_mask', 'chain_lens', 'res_info', 'binder_chain_id'])

In [126]:
seed_data

{'msas': tensor([[[0]],
 
         [[0]],
 
         [[0]]]),
 'features': tensor([[[[0.]]],
 
 
         [[[0.]]],
 
 
         [[[0.]]]]),
 'ppoe': tensor([[[[0.]]],
 
 
         [[[0.]]],
 
 
         [[[0.]]]]),
 'seq_lens': tensor([117, 119, 119]),
 'focuses': tensor([[[0.]],
 
         [[0.]],
 
         [[0.]]], dtype=torch.float64),
 'contact_idxs': tensor([[[0.]],
 
         [[0.]],
 
         [[0.]]], dtype=torch.float64),
 'src_key_mask': tensor([[False],
         [False],
         [False]]),
 'term_lens': tensor([[1, 0],
         [1, 0],
         [1, 0]]),
 'X': tensor([[[[ -8.7290,  -3.6990,  18.7810],
           [ -9.3140,  -4.6870,  17.8840],
           [-10.5750,  -5.3110,  18.4730],
           [-10.7480,  -5.3630,  19.6920]],
 
          [[-11.4510,  -5.7860,  17.5930],
           [-12.6890,  -6.4290,  18.0000],
           [-12.3770,  -7.8010,  18.5760],
           [-11.3670,  -8.4160,  18.2290]],
 
          [[-13.2370,  -8.2860,  19.4620],
           [-13.1010,  -9.6

In [78]:
seed_data['seq_lens'].shape

torch.Size([3])

In [79]:
seed_data['ids']

['4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9353-311-12_seed-4FXE-ARG81-relax-noHyd_E_B_E7_19558_264_255_connector-659-302-7_seed-4FXE-ARG81-relax-noHyd_E_B_E27_18950_417_380',
 '4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-13667-708-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247',
 '4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247']

In [80]:
seed_data['ids'][2] 

'4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247'

In [81]:
complex_data['ids'][0]

'seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247'

In [83]:
# are we comparing the same thing..
seed_data['ids'][2] == '4FXE-ARG81-relax-noHyd_E__' + complex_data['ids'][0]

True

In [84]:
seed_data['seq_lens']

tensor([117, 119, 119])

In [85]:
complex_data['seqs'][0]

tensor([ 0, 19,  4,  9,  2,  4,  2,  3, 14,  0,  9,  8,  3, 18, 14,  8,  9,  5,
        15, 16, 17, 14,  3, 13,  9,  8,  8,  8,  9, 17,  3, 17,  9,  3, 15, 12,
        14,  7,  3,  0, 11,  8,  9, 14,  5, 10, 12,  2,  1, 19,  8,  7,  8,  9,
        14, 15, 15,  5, 19, 14,  9, 17, 19, 13, 17,  7,  2,  3,  8, 17, 17, 17,
         4, 17,  7, 15, 17,  5,  8, 14,  3, 14, 13, 12,  4,  6,  2,  9, 15,  0,
         3,  5, 15,  2,  3,  2,  0,  3,  9, 17,  3,  7, 17,  8,  3, 14, 12,  6,
        16, 17, 15,  0,  2, 11,  7, 15, 17, 12, 13])

In [86]:
seed_data['seqs'][2]

tensor([ 0, 19,  4,  9,  2,  4,  2,  3, 14,  0,  9,  8,  3, 18, 14,  8,  9,  5,
        15, 16, 17, 14,  3, 13,  9,  8,  8,  8,  9, 17,  3, 17,  9,  3, 15, 12,
        14,  7,  3,  0, 11,  8,  9, 14,  5, 10, 12,  2,  1, 19,  8,  7,  8,  9,
        14, 15, 15,  5, 19, 14,  9, 17, 19, 13, 17,  7,  2,  3,  8, 17, 17, 17,
         4, 17,  7, 15, 17,  5,  8, 14,  3, 14, 13, 12,  4,  6,  2,  9, 15,  0,
         3,  5, 15,  2,  3,  2,  0,  3,  9, 17,  3,  7, 17,  8,  3, 14, 12,  6,
        16, 17, 15,  0,  2, 11,  7, 15, 17, 12, 13])

In [87]:
seed_data['seqs'][2] == complex_data['seqs'][0]

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True])

First residue of target is missing when scoring in seed mode?...

In [88]:
complex_data['res_info'][0]

[('E', '2'),
 ('E', '3'),
 ('E', '4'),
 ('E', '5'),
 ('E', '6'),
 ('E', '7'),
 ('E', '8'),
 ('E', '9'),
 ('E', '10'),
 ('E', '11'),
 ('E', '12'),
 ('E', '13'),
 ('E', '14'),
 ('E', '15'),
 ('E', '16'),
 ('E', '17'),
 ('E', '18'),
 ('E', '19'),
 ('E', '20'),
 ('E', '21'),
 ('E', '22'),
 ('E', '23'),
 ('E', '24'),
 ('E', '25'),
 ('E', '26'),
 ('E', '27'),
 ('E', '28'),
 ('E', '29'),
 ('E', '30'),
 ('E', '31'),
 ('E', '32'),
 ('E', '33'),
 ('E', '34'),
 ('E', '35'),
 ('E', '36'),
 ('E', '37'),
 ('E', '38'),
 ('E', '39'),
 ('E', '40'),
 ('E', '41'),
 ('E', '42'),
 ('E', '43'),
 ('E', '44'),
 ('E', '45'),
 ('E', '46'),
 ('E', '47'),
 ('E', '48'),
 ('E', '49'),
 ('E', '50'),
 ('E', '51'),
 ('E', '52'),
 ('E', '53'),
 ('E', '54'),
 ('E', '55'),
 ('E', '56'),
 ('E', '57'),
 ('E', '58'),
 ('E', '59'),
 ('E', '60'),
 ('E', '61'),
 ('E', '62'),
 ('E', '63'),
 ('E', '64'),
 ('E', '65'),
 ('E', '66'),
 ('E', '67'),
 ('E', '68'),
 ('E', '69'),
 ('E', '70'),
 ('E', '71'),
 ('E', '72'),
 ('E', '73'),


In [89]:
seed_data['res_info'][2]

[('E', '2'),
 ('E', '3'),
 ('E', '4'),
 ('E', '5'),
 ('E', '6'),
 ('E', '7'),
 ('E', '8'),
 ('E', '9'),
 ('E', '10'),
 ('E', '11'),
 ('E', '12'),
 ('E', '13'),
 ('E', '14'),
 ('E', '15'),
 ('E', '16'),
 ('E', '17'),
 ('E', '18'),
 ('E', '19'),
 ('E', '20'),
 ('E', '21'),
 ('E', '22'),
 ('E', '23'),
 ('E', '24'),
 ('E', '25'),
 ('E', '26'),
 ('E', '27'),
 ('E', '28'),
 ('E', '29'),
 ('E', '30'),
 ('E', '31'),
 ('E', '32'),
 ('E', '33'),
 ('E', '34'),
 ('E', '35'),
 ('E', '36'),
 ('E', '37'),
 ('E', '38'),
 ('E', '39'),
 ('E', '40'),
 ('E', '41'),
 ('E', '42'),
 ('E', '43'),
 ('E', '44'),
 ('E', '45'),
 ('E', '46'),
 ('E', '47'),
 ('E', '48'),
 ('E', '49'),
 ('E', '50'),
 ('E', '51'),
 ('E', '52'),
 ('E', '53'),
 ('E', '54'),
 ('E', '55'),
 ('E', '56'),
 ('E', '57'),
 ('E', '58'),
 ('E', '59'),
 ('E', '60'),
 ('E', '61'),
 ('E', '62'),
 ('E', '63'),
 ('E', '64'),
 ('E', '65'),
 ('E', '66'),
 ('E', '67'),
 ('E', '68'),
 ('E', '69'),
 ('E', '70'),
 ('E', '71'),
 ('E', '72'),
 ('E', '73'),


In [91]:
seed_data['res_info'][2] == complex_data['res_info'][0]

True

# Compare all features

In [96]:
import torch

In [110]:
seed_data.keys()

dict_keys(['msas', 'features', 'ppoe', 'seq_lens', 'focuses', 'contact_idxs', 'src_key_mask', 'term_lens', 'X', 'x_mask', 'seqs', 'ids', 'chain_idx', 'gvp_data', 'sortcery_seqs', 'sortcery_nrgs', 'sscore', 'flex', 'flex_mask', 'chain_lens', 'res_info', 'binder_chain_id'])

In [112]:
complex_data.keys()

dict_keys(['msas', 'features', 'ppoe', 'seq_lens', 'focuses', 'contact_idxs', 'src_key_mask', 'term_lens', 'X', 'x_mask', 'seqs', 'ids', 'chain_idx', 'gvp_data', 'sortcery_seqs', 'sortcery_nrgs', 'sscore', 'flex', 'flex_mask', 'chain_lens', 'res_info', 'binder_chain_id'])

In [111]:
set(seed_data.keys()) - set(complex_data.keys())

set()

In [108]:
set(complex_data.keys()) - set(seed_data.keys())

set()

In [121]:
for k in seed_data:
    try:
        if isinstance(seed_data[k][2],torch.Tensor):
            if not torch.equal(seed_data[k][2],complex_data[k][0]):
                print(k,'is not equal')
            else:
                print(k,'is equal')
        else:
            if not seed_data[k][2] == complex_data[k][0]:
                print(k,'is not equal!!!')
            else:
                print(k,'is equal')
    except Exception as E:
        print('woops',k,E)
        if seed_data[k] == complex_data[k]:
            print('but they are the same')

msas is equal
features is equal
ppoe is equal
seq_lens is equal
focuses is equal
contact_idxs is equal
src_key_mask is equal
term_lens is equal
X is equal
x_mask is equal
seqs is equal
ids is not equal!!!
chain_idx is equal
gvp_data is not equal!!!
woops sortcery_seqs list index out of range
but they are the same
woops sortcery_nrgs list index out of range
but they are the same
woops sscore list index out of range
but they are the same
woops flex 'NoneType' object is not subscriptable
but they are the same
woops flex_mask 'NoneType' object is not subscriptable
but they are the same
chain_lens is equal
res_info is equal
binder_chain_id is equal


In [122]:
seed_data['ids'][2]

'4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247'

In [124]:
complex_data['ids'][0]

'seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247'

In [119]:
seed_data['gvp_data'][2]

Data(x=[119, 3], edge_index=[2, 3570], seq=[119], name='4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247', node_s=[119, 6], node_v=[119, 3, 3], edge_s=[3570, 32], edge_v=[3570, 1, 3], mask=[119])

In [125]:
complex_data['gvp_data'][0]

Data(x=[119, 3], edge_index=[2, 3570], seq=[119], name='seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247', node_s=[119, 6], node_v=[119, 3, 3], edge_s=[3570, 32], edge_v=[3570, 1, 3], mask=[119])

These are basically the same except for the name