In [20]:
import pickle
import torch

# Targets (these should be the same)

In [12]:
with open('02_scoreSeeds_2/net_out_2_4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247_target.pkl', 'rb') as file:
    netout_seed = pickle.load(file)
netout_seed.keys()

dict_keys(['id', 'etab', 'E_idx', 'sscore', 'seq', 'res_info'])

In [13]:
netout_seed['id']

'4FXE-ARG81-relax-noHyd_E_'

In [25]:
netout_seed['E_idx'].shape

torch.Size([82, 30])

In [14]:
with open('02_scoreSeeds_4/net_out_0_seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247_target.pkl', 'rb') as file:
    netout_complex = pickle.load(file)
netout_complex.keys()

dict_keys(['id', 'etab', 'E_idx', 'sscore', 'seq', 'res_info'])

In [15]:
netout_complex['id']

'seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9353-311-12_seed-4FXE-ARG81-relax-noHyd_E_B_E7_19558_264_255_connector-659-302-7_seed-4FXE-ARG81-relax-noHyd_E_B_E27_18950_417_380_target'

In [26]:
netout_complex['E_idx'].shape

torch.Size([82, 30])

In [29]:
netout_seed['E_idx']

tensor([[ 0,  1, 33,  ..., 63, 62, 73],
        [ 1,  2,  0,  ..., 37, 27, 47],
        [ 2,  1,  3,  ..., 36, 74, 25],
        ...,
        [79, 78, 80,  ..., 17,  8, 11],
        [80, 81, 79,  ...,  9, 43, 40],
        [81, 80, 79,  ..., 21, 24, 40]])

In [27]:
netout_complex['E_idx']

tensor([[ 0,  1, 33,  ..., 63, 62, 73],
        [ 1,  2,  0,  ..., 37, 27, 47],
        [ 2,  1,  3,  ..., 36, 74, 25],
        ...,
        [79, 78, 80,  ..., 17,  8, 11],
        [80, 81, 79,  ...,  9, 43, 40],
        [81, 80, 79,  ..., 21, 24, 40]])

In [ ]:
torch.equal(netout_seed['E_idx'],b)

In [30]:
netout_seed['E_idx'] == netout_complex['E_idx']

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])

In [32]:
def compare_out(a,b):
    for k in a:
        try:
            if isinstance(a[k],torch.Tensor):
                if not torch.equal(a[k],b[k]):
                    print(k,'is not equal')
                else:
                    print(k,'is equal')
            else:
                if not a[k] == b[k]:
                    print(k,'is not equal!!!')
                else:
                    print(k,'is equal')
        except Exception as E:
            print('woops',k,E)
            if a[k] == b:
                print('but they are the same')

compare_out(netout_complex,netout_seed)

id is not equal!!!
etab is equal
E_idx is equal
sscore is equal
seq is equal
res_info is equal


# Complex (these may not be the same)

In [51]:
with open('02_scoreSeeds_2/net_out_2_4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247_complex.pkl', 'rb') as file:
    netout_seed = pickle.load(file)[0]
netout_seed.keys()

dict_keys(['id', 'etab', 'E_idx', 'sscore', 'seq', 'res_info'])

In [52]:
netout_seed['id']

'4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9353-311-12_seed-4FXE-ARG81-relax-noHyd_E_B_E7_19558_264_255_connector-659-302-7_seed-4FXE-ARG81-relax-noHyd_E_B_E27_18950_417_380'

In [53]:
netout_seed['E_idx'].shape

torch.Size([117, 30])

In [54]:
netout_seed['res_info']

[('E', '2'),
 ('E', '3'),
 ('E', '4'),
 ('E', '5'),
 ('E', '6'),
 ('E', '7'),
 ('E', '8'),
 ('E', '9'),
 ('E', '10'),
 ('E', '11'),
 ('E', '12'),
 ('E', '13'),
 ('E', '14'),
 ('E', '15'),
 ('E', '16'),
 ('E', '17'),
 ('E', '18'),
 ('E', '19'),
 ('E', '20'),
 ('E', '21'),
 ('E', '22'),
 ('E', '23'),
 ('E', '24'),
 ('E', '25'),
 ('E', '26'),
 ('E', '27'),
 ('E', '28'),
 ('E', '29'),
 ('E', '30'),
 ('E', '31'),
 ('E', '32'),
 ('E', '33'),
 ('E', '34'),
 ('E', '35'),
 ('E', '36'),
 ('E', '37'),
 ('E', '38'),
 ('E', '39'),
 ('E', '40'),
 ('E', '41'),
 ('E', '42'),
 ('E', '43'),
 ('E', '44'),
 ('E', '45'),
 ('E', '46'),
 ('E', '47'),
 ('E', '48'),
 ('E', '49'),
 ('E', '50'),
 ('E', '51'),
 ('E', '52'),
 ('E', '53'),
 ('E', '54'),
 ('E', '55'),
 ('E', '56'),
 ('E', '57'),
 ('E', '58'),
 ('E', '59'),
 ('E', '60'),
 ('E', '61'),
 ('E', '62'),
 ('E', '63'),
 ('E', '64'),
 ('E', '65'),
 ('E', '66'),
 ('E', '67'),
 ('E', '68'),
 ('E', '69'),
 ('E', '70'),
 ('E', '71'),
 ('E', '72'),
 ('E', '73'),


In [55]:
with open('02_scoreSeeds_4/net_out_0_seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247_complex.pkl', 'rb') as file:
    netout_complex = pickle.load(file)[0]
netout_complex.keys()

dict_keys(['id', 'etab', 'E_idx', 'sscore', 'seq', 'res_info'])

In [56]:
netout_complex['id']

'seed-4FXE-ARG81-relax-noHyd_E_B_E41_12262_133_404_connector-14590-287-8_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9218-393-12_seed-4FXE-ARG81-relax-noHyd_E_B_E5_18353_195_247'

In [57]:
netout_complex['E_idx'].shape

torch.Size([119, 30])

In [58]:
netout_complex['res_info']

[('E', '2'),
 ('E', '3'),
 ('E', '4'),
 ('E', '5'),
 ('E', '6'),
 ('E', '7'),
 ('E', '8'),
 ('E', '9'),
 ('E', '10'),
 ('E', '11'),
 ('E', '12'),
 ('E', '13'),
 ('E', '14'),
 ('E', '15'),
 ('E', '16'),
 ('E', '17'),
 ('E', '18'),
 ('E', '19'),
 ('E', '20'),
 ('E', '21'),
 ('E', '22'),
 ('E', '23'),
 ('E', '24'),
 ('E', '25'),
 ('E', '26'),
 ('E', '27'),
 ('E', '28'),
 ('E', '29'),
 ('E', '30'),
 ('E', '31'),
 ('E', '32'),
 ('E', '33'),
 ('E', '34'),
 ('E', '35'),
 ('E', '36'),
 ('E', '37'),
 ('E', '38'),
 ('E', '39'),
 ('E', '40'),
 ('E', '41'),
 ('E', '42'),
 ('E', '43'),
 ('E', '44'),
 ('E', '45'),
 ('E', '46'),
 ('E', '47'),
 ('E', '48'),
 ('E', '49'),
 ('E', '50'),
 ('E', '51'),
 ('E', '52'),
 ('E', '53'),
 ('E', '54'),
 ('E', '55'),
 ('E', '56'),
 ('E', '57'),
 ('E', '58'),
 ('E', '59'),
 ('E', '60'),
 ('E', '61'),
 ('E', '62'),
 ('E', '63'),
 ('E', '64'),
 ('E', '65'),
 ('E', '66'),
 ('E', '67'),
 ('E', '68'),
 ('E', '69'),
 ('E', '70'),
 ('E', '71'),
 ('E', '72'),
 ('E', '73'),


In [46]:
def compare_out(a,b):
    for k in a:
        try:
            if isinstance(a[k],torch.Tensor):
                if not torch.equal(a[k],b[k]):
                    print(k,'is not equal')
                else:
                    print(k,'is equal')
            else:
                if not a[k] == b[k]:
                    print(k,'is not equal!!!')
                else:
                    print(k,'is equal')
        except Exception as E:
            print('woops',k,E)
            if a[k] == b:
                print('but they are the same')

compare_out(netout_complex,netout_seed)

id is not equal!!!
etab is not equal
E_idx is not equal
sscore is not equal
seq is not equal
res_info is not equal!!!


# Complex (compare the first fused bb)

In [59]:
with open('02_scoreSeeds_2/net_out_0_4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9353-311-12_seed-4FXE-ARG81-relax-noHyd_E_B_E7_19558_264_255_connector-659-302-7_seed-4FXE-ARG81-relax-noHyd_E_B_E27_18950_417_380_complex.pkl', 'rb') as file:
    netout_seed = pickle.load(file)[0]
netout_seed.keys()

dict_keys(['id', 'etab', 'E_idx', 'sscore', 'seq', 'res_info'])

In [60]:
netout_seed['id']

'4FXE-ARG81-relax-noHyd_E__seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9353-311-12_seed-4FXE-ARG81-relax-noHyd_E_B_E7_19558_264_255_connector-659-302-7_seed-4FXE-ARG81-relax-noHyd_E_B_E27_18950_417_380'

In [62]:
netout_seed['E_idx'].shape

torch.Size([117, 30])

In [63]:
netout_seed['res_info']

[('E', '2'),
 ('E', '3'),
 ('E', '4'),
 ('E', '5'),
 ('E', '6'),
 ('E', '7'),
 ('E', '8'),
 ('E', '9'),
 ('E', '10'),
 ('E', '11'),
 ('E', '12'),
 ('E', '13'),
 ('E', '14'),
 ('E', '15'),
 ('E', '16'),
 ('E', '17'),
 ('E', '18'),
 ('E', '19'),
 ('E', '20'),
 ('E', '21'),
 ('E', '22'),
 ('E', '23'),
 ('E', '24'),
 ('E', '25'),
 ('E', '26'),
 ('E', '27'),
 ('E', '28'),
 ('E', '29'),
 ('E', '30'),
 ('E', '31'),
 ('E', '32'),
 ('E', '33'),
 ('E', '34'),
 ('E', '35'),
 ('E', '36'),
 ('E', '37'),
 ('E', '38'),
 ('E', '39'),
 ('E', '40'),
 ('E', '41'),
 ('E', '42'),
 ('E', '43'),
 ('E', '44'),
 ('E', '45'),
 ('E', '46'),
 ('E', '47'),
 ('E', '48'),
 ('E', '49'),
 ('E', '50'),
 ('E', '51'),
 ('E', '52'),
 ('E', '53'),
 ('E', '54'),
 ('E', '55'),
 ('E', '56'),
 ('E', '57'),
 ('E', '58'),
 ('E', '59'),
 ('E', '60'),
 ('E', '61'),
 ('E', '62'),
 ('E', '63'),
 ('E', '64'),
 ('E', '65'),
 ('E', '66'),
 ('E', '67'),
 ('E', '68'),
 ('E', '69'),
 ('E', '70'),
 ('E', '71'),
 ('E', '72'),
 ('E', '73'),


In [64]:
with open('02_scoreSeeds_4/net_out_0_seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9353-311-12_seed-4FXE-ARG81-relax-noHyd_E_B_E7_19558_264_255_connector-659-302-7_seed-4FXE-ARG81-relax-noHyd_E_B_E27_18950_417_380_complex.pkl', 'rb') as file:
    netout_complex = pickle.load(file)[0]
netout_complex.keys()

dict_keys(['id', 'etab', 'E_idx', 'sscore', 'seq', 'res_info'])

In [65]:
netout_complex['id']

'seed-4FXE-ARG81-relax-noHyd-48-66__0_connector-9353-311-12_seed-4FXE-ARG81-relax-noHyd_E_B_E7_19558_264_255_connector-659-302-7_seed-4FXE-ARG81-relax-noHyd_E_B_E27_18950_417_380'

In [66]:
netout_complex['E_idx'].shape

torch.Size([117, 30])

In [67]:
netout_complex['res_info']

[('E', '2'),
 ('E', '3'),
 ('E', '4'),
 ('E', '5'),
 ('E', '6'),
 ('E', '7'),
 ('E', '8'),
 ('E', '9'),
 ('E', '10'),
 ('E', '11'),
 ('E', '12'),
 ('E', '13'),
 ('E', '14'),
 ('E', '15'),
 ('E', '16'),
 ('E', '17'),
 ('E', '18'),
 ('E', '19'),
 ('E', '20'),
 ('E', '21'),
 ('E', '22'),
 ('E', '23'),
 ('E', '24'),
 ('E', '25'),
 ('E', '26'),
 ('E', '27'),
 ('E', '28'),
 ('E', '29'),
 ('E', '30'),
 ('E', '31'),
 ('E', '32'),
 ('E', '33'),
 ('E', '34'),
 ('E', '35'),
 ('E', '36'),
 ('E', '37'),
 ('E', '38'),
 ('E', '39'),
 ('E', '40'),
 ('E', '41'),
 ('E', '42'),
 ('E', '43'),
 ('E', '44'),
 ('E', '45'),
 ('E', '46'),
 ('E', '47'),
 ('E', '48'),
 ('E', '49'),
 ('E', '50'),
 ('E', '51'),
 ('E', '52'),
 ('E', '53'),
 ('E', '54'),
 ('E', '55'),
 ('E', '56'),
 ('E', '57'),
 ('E', '58'),
 ('E', '59'),
 ('E', '60'),
 ('E', '61'),
 ('E', '62'),
 ('E', '63'),
 ('E', '64'),
 ('E', '65'),
 ('E', '66'),
 ('E', '67'),
 ('E', '68'),
 ('E', '69'),
 ('E', '70'),
 ('E', '71'),
 ('E', '72'),
 ('E', '73'),


In [68]:
def compare_out(a,b):
    for k in a:
        try:
            if isinstance(a[k],torch.Tensor):
                if not torch.equal(a[k],b[k]):
                    print(k,'is not equal')
                else:
                    print(k,'is equal')
            else:
                if not a[k] == b[k]:
                    print(k,'is not equal!!!')
                else:
                    print(k,'is equal')
        except Exception as E:
            print('woops',k,E)
            if a[k] == b:
                print('but they are the same')

compare_out(netout_complex,netout_seed)

id is not equal!!!
etab is not equal
E_idx is equal
sscore is not equal
seq is equal
res_info is equal


In [72]:
netout_seed['sscore']

tensor([ 1.9180,  1.5367,  0.7967,  0.8678, -0.3158,  0.5129,  0.8892,  1.4198,
         0.0732, -0.9211, -0.0950, -0.6409, -0.5813, -0.3314,  0.4854, -0.0731,
         0.7111,  0.4252, -0.3437, -0.8246, -1.2877, -0.8978, -1.8669, -1.7626,
        -1.7788, -1.7624, -1.6719, -1.8871, -1.7469, -1.6742, -1.4152, -1.2467,
        -0.3364,  1.2637,  0.5603,  1.0943,  1.2335,  1.5934,  1.6898,  1.3795,
         1.8456,  0.8739,  1.4497,  1.4742,  1.7502,  1.4445,  1.4753,  1.8217,
         1.3599,  0.1960,  0.8999, -0.1133,  0.7308,  0.9289,  1.7231,  1.6948,
         2.1277,  1.2288,  0.8020,  0.2561, -0.3186, -0.6042, -0.4631,  0.5595,
         0.6495,  1.6595,  1.9983,  1.6588,  1.4782,  2.1413,  0.7108,  0.2241,
        -0.6178,  0.0621,  0.0114,  1.1560,  0.4449,  0.8574,  2.1722,  1.7968,
         2.3945,  2.0719,  0.7881,  0.5354, -0.6030, -0.7670, -1.1905, -1.4703,
        -1.2980, -1.3399, -1.8232, -2.0308, -1.8322, -1.7051, -1.9972, -1.7226,
        -1.5104, -1.8569, -0.9602, -1.11

In [76]:
netout_seed['sscore'].sum()

tensor(36.4796)

In [77]:
netout_complex['sscore'].shape

torch.Size([117])

In [75]:
netout_complex['sscore']

tensor([ 0.5538,  0.4566, -0.2897,  0.5131, -1.7901, -1.0002,  0.2060, -0.4437,
        -1.4581, -1.4870, -0.9295, -1.4690, -1.6663, -0.9656, -0.8693, -0.1027,
         0.0870,  0.3496, -1.0537, -1.2963, -1.3552, -0.9164, -2.0326, -2.3308,
        -1.6737, -1.8762, -1.7431, -1.6423, -1.6521, -1.1341, -1.3505, -1.3356,
        -0.1254,  0.2404,  2.3544,  0.9284,  2.0889,  1.7822,  0.3518,  0.2076,
         1.0170,  0.0795, -0.0313,  1.1173,  0.5626,  0.1428,  0.4099,  1.4403,
        -0.8369, -0.7473, -1.2389, -0.7886,  0.0877,  0.2057,  0.9700,  0.8374,
         1.6231,  1.2166,  0.3529, -0.8243, -1.3245, -1.6623, -1.2803, -1.2738,
        -0.9465,  0.0219,  0.8731,  0.4879,  0.5666,  1.8052, -0.7221, -0.9014,
        -1.6169, -1.4536, -1.1342, -1.1532, -1.1610,  1.5692,  0.7065,  1.0152,
         2.1404,  1.6110,  1.4763, -1.3345, -1.2082, -1.3633, -1.5493, -1.8237,
        -2.0297, -1.6370, -1.8856, -2.0903, -2.1478, -1.7402, -1.9713, -2.1510,
        -2.2693, -1.7532, -1.8506, -1.89

In [74]:
netout_complex['sscore'].sum()

tensor(-41.4679)